apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui-sourcecode-tst
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui-sourcecode-tst
  template:
    metadata:
      labels:
        app: guestbook-ui-sourcecode-tst
        tst: tst-111127799899099j445454545454kkk
    spec:
      containers:
      - image: omniregistry/back-end:9ceceb5e31a48da90e8d7abb9c71eb91fd2cc538-1
        name: guestbook-ui-tst
        ports:
        - containerPort: 80
