apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui-sourcecode-tst
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui-sourcecode-tst
  template:
    metadata:
      labels:
        app: guestbook-ui-sourcecode-tst
        tst: tst-1111277998
    spec:
      containers:
      - image: omniregistry/back-end:83451e30def13e142d804dd7ecede5869ad22fba
        name: guestbook-ui-tst
        ports:
        - containerPort: 80
